export const atividadesMock = {
  pending: [
    {
      id: 'a1',
      title: 'Entrega do artigo de UX',
      subject: 'Interação Humano-Computador',
      dueLabel: 'Vence hoje',
      dueUrgency: 'high',
    },
    {
      id: 'a2',
      title: 'Lista de exercícios 04',
      subject: 'Banco de Dados II',
      dueLabel: 'Em 2 dias',
      dueUrgency: 'medium',
    },
    {
      id: 'a3',
      title: 'Relatório de requisitos — Sprint 2',
      subject: 'Engenharia de Software',
      dueLabel: 'Em 5 dias',
      dueUrgency: 'low',
    },
    {
      id: 'a4',
      title: 'Prova P2',
      subject: 'Cálculo II',
      dueLabel: 'Em 7 dias',
      dueUrgency: 'medium',
    },
    {
      id: 'a5',
      title: 'Trabalho em grupo — topologia de redes',
      subject: 'Redes de Computadores',
      dueLabel: 'Em 10 dias',
      dueUrgency: 'low',
    },
  ],
  delivered: [
    {
      id: 'd1',
      title: 'Diagrama ER — Projeto Final',
      subject: 'Banco de Dados II',
      deliveredAt: '20/04/2026',
      deliveredLabel: 'Entregue em 20/04',
      status: 'graded',
      grade: '9.5',
      feedback: 'Excelente modelagem. O diagrama está bem estruturado e as relações estão corretas. Apenas a cardinalidade de uma entidade precisaria de revisão menor, mas o trabalho foi muito bem executado.',
      attachmentName: 'Diagrama_ER_Final.pdf',
    },
    {
      id: 'd2',
      title: 'Artigo sobre heurísticas de Nielsen',
      subject: 'Interação Humano-Computador',
      deliveredAt: '15/04/2026',
      deliveredLabel: 'Entregue em 15/04',
      status: 'graded',
      grade: '10.0',
      feedback: 'Trabalho excelente. Análise completa e bem embasada das 10 heurísticas com exemplos práticos e relevantes. Redação clara e referências adequadas.',
      attachmentName: 'Artigo_Heuristicas_Nielsen.pdf',
    },
    {
      id: 'd3',
      title: 'Lista de exercícios 03',
      subject: 'Banco de Dados II',
      deliveredAt: '10/04/2026',
      deliveredLabel: 'Entregue em 10/04',
      status: 'graded',
      grade: '8.0',
      feedback: 'Bom trabalho. As questões 1 a 4 estão corretas. A questão 5 apresentou erro na normalização para a 3FN — revise o conceito de dependência transitiva.',
      attachmentName: 'Lista_03_BD2.pdf',
    },
    {
      id: 'd4',
      title: 'Trabalho — Gerência de Memória',
      subject: 'Sistemas Operacionais',
      deliveredAt: '25/04/2026',
      deliveredLabel: 'Entregue em 25/04',
      status: 'submitted',
      grade: null,
      feedback: null,
      attachmentName: 'Trabalho_Gerencia_Memoria.pdf',
    },
    {
      id: 'd5',
      title: 'Relatório de lab — Circuitos RC',
      subject: 'Física Aplicada',
      deliveredAt: '22/04/2026',
      deliveredLabel: 'Entregue em 22/04',
      status: 'submitted',
      grade: null,
      feedback: null,
      attachmentName: 'Relatorio_Lab_Fisica.pdf',
    },
  ],
};
