export const notasMock = [
  {
    id: 'eng-sw',
    subject: 'Engenharia de Software',
    teacher: 'Prof. Ana Ribeiro',
    average: 8.5,
    situation: 'Aprovado',
    attendance: 87,
    grades: [
      { label: 'P1', value: 7.5 },
      { label: 'Trabalho — Elicitação', value: 9.0 },
      { label: 'P2', value: null },
    ],
  },
  {
    id: 'ihc',
    subject: 'Interação Humano-Computador',
    teacher: 'Prof. Bruno Melo',
    average: 9.3,
    situation: 'Aprovado',
    attendance: 92,
    grades: [
      { label: 'P1', value: 9.5 },
      { label: 'Artigo — Heurísticas', value: 10.0 },
      { label: 'Entrega de UX', value: null },
    ],
  },
  {
    id: 'bd2',
    subject: 'Banco de Dados II',
    teacher: 'Prof. Fernanda Lima',
    average: 8.6,
    situation: 'Aprovado',
    attendance: 78,
    grades: [
      { label: 'P1', value: 8.0 },
      { label: 'Lista 01', value: 9.5 },
      { label: 'Lista 02', value: 8.0 },
      { label: 'Diagrama ER', value: 9.5 },
      { label: 'P2', value: null },
    ],
  },
  {
    id: 'calculo',
    subject: 'Cálculo II',
    teacher: 'Prof. Ricardo Souza',
    average: 6.2,
    situation: 'Em risco',
    attendance: 71,
    grades: [
      { label: 'P1', value: 6.5 },
      { label: 'Lista', value: 7.0 },
      { label: 'P2', value: null },
    ],
  },
  {
    id: 'fisica',
    subject: 'Física Aplicada',
    teacher: 'Prof. Carla Andrade',
    average: 7.5,
    situation: 'Aprovado',
    attendance: 83,
    grades: [
      { label: 'P1', value: 7.5 },
      { label: 'Relatório de lab', value: 8.0 },
      { label: 'P2', value: null },
    ],
  },
];
