export const avisosMock = {
  notices: [
    {
      id: 'n1',
      title: 'Reserva de matrícula aberta — 2026/2',
      summary: 'O período de reserva de matrícula para o próximo semestre está aberto. Prazo até 15/05/2026.',
      tag: 'Institucional',
      isImportant: true,
      postedAt: 'Hoje',
    },
    {
      id: 'n2',
      title: 'Semana Acadêmica SATC 2026',
      summary: 'Inscrições abertas para palestras, minicursos e workshops. Evento de 12 a 16 de maio.',
      tag: 'Evento',
      isImportant: false,
      postedAt: 'Hoje',
    },
    {
      id: 'n3',
      title: 'Atualização do Regulamento Acadêmico',
      summary: 'O regulamento foi atualizado. Consulte o documento completo no portal institucional.',
      tag: 'Institucional',
      isImportant: false,
      postedAt: '3 dias atrás',
    },
    {
      id: 'n4',
      title: 'Prazo para solicitação de aproveitamento de estudos',
      summary: 'Solicitações de aproveitamento de disciplinas devem ser feitas até 05/05.',
      tag: 'Acadêmico',
      isImportant: true,
      postedAt: '5 dias atrás',
    },
    {
      id: 'n5',
      title: 'Biblioteca: novos títulos disponíveis',
      summary: 'Foram adicionados 120 novos títulos ao acervo digital. Acesse pelo portal.',
      tag: 'Biblioteca',
      isImportant: false,
      postedAt: '1 semana atrás',
    },
  ],
  poll: {
    id: 'p1',
    question: 'Qual horário vocês preferem para a apresentação do trabalho final?',
    createdBy: 'Prof. Ana Ribeiro',
    totalVotes: 18,
    voted: false,
    options: [
      { id: 'o1', label: 'Terça — 19h30', votes: 8 },
      { id: 'o2', label: 'Quinta — 19h00', votes: 6 },
      { id: 'o3', label: 'Sábado — 08h00', votes: 4 },
    ],
  },
  chat: [
    {
      id: 'c1',
      author: 'Juliana Melo',
      initials: 'JM',
      message: 'Alguém já fez a lista 04 de BD? Tô com dúvida na questão 3.',
      time: '18:42',
      isMine: false,
    },
    {
      id: 'c2',
      author: 'Pedro Alves',
      initials: 'PA',
      message: 'Sim! Precisa normalizar até a 3FN. Manda mensagem pra mim depois.',
      time: '18:45',
      isMine: false,
    },
    {
      id: 'c3',
      author: 'Mateus',
      initials: 'ML',
      message: 'Pessoal, lembrem que a aula de amanhã é online. Link no portal.',
      time: '18:50',
      isMine: true,
    },
    {
      id: 'c4',
      author: 'Camila Rocha',
      initials: 'CR',
      message: 'Obrigada pelo aviso 👍',
      time: '18:52',
      isMine: false,
    },
  ],
};
