export const aulasMock = {
  today: 'ter',
  schedule: {
    dom: [],
    seg: [
      {
        id: 's1',
        subject: 'Cálculo II',
        teacher: 'Prof. Ricardo Souza',
        startsAt: '19:00',
        endsAt: '20:30',
        format: 'presencial',
        room: '202',
        callLink: null,
        status: 'done',
      },
      {
        id: 's2',
        subject: 'Física Aplicada',
        teacher: 'Prof. Carla Andrade',
        startsAt: '20:45',
        endsAt: '22:15',
        format: 'presencial',
        room: '110',
        callLink: null,
        status: 'done',
      },
    ],
    ter: [
      {
        id: 't1',
        subject: 'Engenharia de Software',
        teacher: 'Prof. Ana Ribeiro',
        startsAt: '19:30',
        endsAt: '21:00',
        format: 'online',
        room: null,
        callLink: 'https://meet.satc.edu.br/engsw',
        status: 'next',
      },
      {
        id: 't2',
        subject: 'Interação Humano-Computador',
        teacher: 'Prof. Bruno Melo',
        startsAt: '21:10',
        endsAt: '22:40',
        format: 'presencial',
        room: '301',
        callLink: null,
        status: 'upcoming',
      },
    ],
    qua: [
      {
        id: 'q1',
        subject: 'Banco de Dados II',
        teacher: 'Prof. Fernanda Lima',
        startsAt: '19:00',
        endsAt: '20:30',
        format: 'presencial',
        room: '103',
        callLink: null,
        status: 'upcoming',
      },
    ],
    qui: [
      {
        id: 'qi1',
        subject: 'Sistemas Operacionais',
        teacher: 'Prof. Marcos Vieira',
        startsAt: '19:00',
        endsAt: '20:30',
        format: 'online',
        room: null,
        callLink: 'https://meet.satc.edu.br/so',
        status: 'upcoming',
      },
      {
        id: 'qi2',
        subject: 'Redes de Computadores',
        teacher: 'Prof. Cláudia Nunes',
        startsAt: '20:45',
        endsAt: '22:15',
        format: 'presencial',
        room: '205',
        callLink: null,
        status: 'upcoming',
      },
    ],
    sex: [],
    sab: [
      {
        id: 'sa1',
        subject: 'Metodologia Científica',
        teacher: 'Prof. Patrícia Santos',
        startsAt: '08:00',
        endsAt: '11:30',
        format: 'presencial',
        room: '401',
        callLink: null,
        status: 'upcoming',
      },
    ],
  },
};
